# Generated by Django 4.2.4 on 2023-08-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auctionlisting_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='listing', to='auctions.comment'),
        ),
    ]
