# Generated by Django 4.2.4 on 2023-08-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auctionlisting_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='auctions'),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='Catagory',
            field=models.ManyToManyField(related_name='listings', to='auctions.catagory'),
        ),
    ]
