# Generated by Django 4.2.4 on 2023-08-29 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_rename_catagory_auctionlisting_catagories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='catagories',
            new_name='categories',
        ),
    ]
