# Generated by Django 4.2.4 on 2023-08-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_rename_catagories_auctionlisting_categories'),
    ]

    operations = [
        migrations.RenameModel('Catagory', 'Category'),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(related_name='watchers', to='auctions.auctionlisting'),
        ),
    ]
